### ISSUE TITLE
[FEAT]: Add pre-commit cache to `_reusable-test-code.yml`

### ISSUE THREAD

**Issue by nfelt14** [tektronix/python-package-ci-cd#10]
### Description

It could be nice to have a `pre-commit` cache so that `pre-commit` can run faster as a part of any `test-code.yml` workflows.

### Additional Information

It could be as simple as adding this step before running tox:

```yaml
- uses: actions/cache@v4
  with:
    path: ~/.cache/pre-commit
    key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
```
